version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_container"
    ports:
      - 80:80
    depends_on:
      - django_app

  django_app:
    image: django_app
    build:
      context: ./
    container_name: "django_container"
    ports:
      - 8001:8001
    command: gunicorn dj_posts_docker.wsgi --bind 0.0.0.0:8001
    env_file:
      - ".env"
    depends_on:
      - db

  db:
    image: mysql
    container_name: "posts_db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=posts_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
